// Youtube API
export const SET_REQUEST_IN_PROCESS = 'SET_REQUEST_IN_PROCESS';
export const SET_REQUEST_ENDED = 'SET_REQUEST_ENDED';
export const SET_REQEUST_ERROR = 'SET_REQEUST_ERROR';
export const LOAD_MORE_INCREMENT = 'LOAD_MORE_INCREMENT';
export const LOAD_MORE_IN_PROCESS = 'LOAD_MORE_IN_PROCESS';
export const LOAD_MORE_ENDED = 'LOAD_MORE_ENDED';
// Bookmarks
export const MOVE_TO_BOOKMARKS = 'MOVE_TO_BOOKMARKS';
export const MOVE_FROM_BOOKMARKS = 'MOVE_FROM_BOOKMARKS';
