// Youtube API
export const SET_REQUEST_IN_PROCESS = 'SET_REQUEST_IN_PROCESS';
export const SET_REQUEST_ENDED = 'SET_REQUEST_ENDED';
export const SET_REQEUST_ERROR = 'SET_REQEUST_ERROR';
// Bookmarks
export const MOVE_TO_BOOKMARKS = 'MOVE_TO_BOOKMARKS';
export const MOVE_FROM_BOOKMARKS = 'MOVE_FROM_BOOKMARKS';
